# .github/workflows/deploy-to-github-pages.yml
name: Deploy documentation to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - docs/**

  workflow_dispatch:

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Deploy documentation
        uses: actions/github-pages-deploy@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: main
          FOLDER: docs/
