# .github/workflows/deploy-to-github-pages.yml
name: Deploy documentation to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - docs/**

  workflow_dispatch:

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          published_dir: docs/
