name: Update World Cup 2026 Simulation Results

on:
  workflow_dispatch:

jobs:
  simulate:
    runs-on: ubuntu-latest

    if: github.actor != 'github-actions'

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install Python
        run: uv python install

      - name: Install dependencies
        run: uv sync --extra dev

      - name: Install CmdStan C++ Toolchain
        # This downloads and compiles the backend required by cmdstanpy
        run: |
          uv run --with cmdstanpy python -c "import cmdstanpy; cmdstanpy.install_cmdstan()"

      - name: Load data
        run: uv run python -c "from src.data.loader import data_pipeline; data_pipeline()"

      - name: Train model
        run: uv run python -m src.simulations.train_2026

      - name: Run simulation
        run: uv run python -m src.simulations.sim_2026

      - name: Commit changes (if any)
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add -A

          if ! git diff --cached --quiet; then
            git commit -m "update simulation results"
            git push
          else
            echo "No changes to commit"
          fi
